import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { run } from "../src/cli.js";
import { HephaestusError } from "../src/errors.js";
import { createMergeRelay, evaluateMergeReadiness, recordMergeResult, saveMergeReadinessReport } from "../src/merge-gate.js";
import { loadState, validateState } from "../src/state.js";
import { loadTestDeclaration, projectFingerprint, saveTestEvidence } from "../src/test-gate.js";
import { writableTemporaryDirectory } from "./helpers/writable-temp.js";

const timestamp = "2026-06-23T12:00:00.000Z";
const state = Object.freeze({ currentPhase: "8", currentTask: "merge-gate", currentBranch: "phase8", currentPr: "https://fixture.invalid/pr/8", assignedAgent: null, attemptCount: 0, blocked: false, usageLimitPaused: false, lastSuccessfulStep: "review-ingestion", reviewStatus: "ingested", mergeStatus: "blocked", containerStatus: "healthy", lastGptDecision: null, nextAction: "merge-readiness" });

function json(file, value) { fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`); }
function reviewState(overrides = {}) { return { attempted: true, ingestionStatus: "succeeded", unresolvedBlockers: 0, dismissedCount: 0, resolvedCount: 1, activeSources: ["CodeRabbit"], unavailableSources: ["Qodo"], mergeBlocked: false, ingestedAt: timestamp, failureReason: null, ...overrides }; }
function input(overrides = {}) { return { project: "demo", phase: "8", currentBranch: "phase8", dirty: false, retest: { implementation: true, review: true }, pr: { number: 8, url: "https://fixture.invalid/pr/8", headBranch: "phase8", baseBranch: "master", status: "OPEN", mergeable: true, headCommit: "abc123" }, approval: { approved: true, approvedBy: "GPT", project: "demo", phase: "8", pr: 8, branch: "phase8", headCommit: "abc123", decidedAt: "2026-06-23T11:00:00.000Z", stale: false }, ...overrides }; }
function items(items = [{ source: "CodeRabbit", externalId: "cr-1", body: "Fixed", actionable: true, status: "resolved", firstSeenAt: timestamp, lastSeenAt: timestamp }]) { return { version: 1, items }; }
function context({ review = reviewState(), reviewItems = items(), evidence = true } = {}) {
  const directory = writableTemporaryDirectory("hephaestus-phase8-");
  for (const name of ["PLAN.md", "BUILDING_REFERENCE.md", "BUILD_LOG.md", "CURRENT_TASK.md"]) fs.writeFileSync(path.join(directory, name), "fixture\n");
  fs.writeFileSync(path.join(directory, "source.txt"), "source\n");
  json(path.join(directory, "STATE.json"), { ...state, review });
  json(path.join(directory, "TESTS.json"), { requiredCommands: [{ id: "unit", outputRequired: true }], watchedFiles: ["source.txt"] });
  fs.mkdirSync(path.join(directory, "out", "review_reports"), { recursive: true });
  json(path.join(directory, "out", "review_reports", "review-items.json"), reviewItems);
  if (evidence) saveTestEvidence(directory, { projectFingerprint: projectFingerprint(directory, loadTestDeclaration(directory)), commands: [{ id: "unit", exitCode: 0, stdout: "ok\n", stderr: "" }] });
  return directory;
}
function gate(projectPath, overrides = {}) { return evaluateMergeReadiness({ projectPath, state: loadState(projectPath), input: input(overrides), now: timestamp }); }
function codes(result) { return result.blockers.map((item) => item.code); }
function cleanup(directory) { fs.rmSync(directory, { recursive: true, force: true }); }
function code(error, expected) { assert.ok(error instanceof HephaestusError); assert.equal(error.code, expected); return true; }
function cliContext(fixture) {
  const directory = writableTemporaryDirectory("hephaestus-phase8-cli-"); const root = path.join(directory, "projects"); const project = path.join(root, "demo"); fs.mkdirSync(project, { recursive: true });
  for (const name of ["PLAN.md", "BUILDING_REFERENCE.md", "BUILD_LOG.md", "CURRENT_TASK.md"]) fs.writeFileSync(path.join(project, name), "fixture\n");
  json(path.join(project, "STATE.json"), state); fs.mkdirSync(path.join(root, "merge-fixtures"), { recursive: true }); json(path.join(root, "merge-fixtures", "fixture.json"), fixture);
  const config = path.join(directory, "config.json"); json(config, { allowedRoot: "./projects", registryPath: "./projects.json", logDirectory: "./logs" }); json(path.join(directory, "projects.json"), { projects: [{ id: "demo", path: "demo" }] });
  return { directory, config, fixture: "merge-fixtures/fixture.json" };
}
function mergeResult() { return { project: "demo", phase: "8", pr: "8", headCommit: "abc123", mergeCommit: "merge456", actor: "approved-executor", mergedAt: timestamp, gateReportPath: "out/merge_reports/phase-8-pr-8-legacy.json" }; }

test("merge blocks without structured test evidence", () => { const p = context({ evidence: false }); try { assert.ok(codes(gate(p)).includes("MISSING_TEST_EVIDENCE")); } finally { cleanup(p); } });
test("merge blocks failed, missing, and outputless test commands", () => { const p = context(); try { saveTestEvidence(p, { projectFingerprint: projectFingerprint(p, loadTestDeclaration(p)), commands: [{ id: "unit", exitCode: 1, stdout: "", stderr: "failed" }] }); assert.ok(codes(gate(p)).includes("FAILED_TESTS")); saveTestEvidence(p, { projectFingerprint: projectFingerprint(p, loadTestDeclaration(p)), commands: [] }); assert.ok(codes(gate(p)).includes("MISSING_REQUIRED_TEST_COMMAND")); saveTestEvidence(p, { projectFingerprint: projectFingerprint(p, loadTestDeclaration(p)), commands: [{ id: "unit", exitCode: 0, stdout: "", stderr: "" }] }); assert.ok(codes(gate(p)).includes("MISSING_TEST_OUTPUT")); } finally { cleanup(p); } });
test("merge blocks a required test command without an exit code", () => { const p = context(); try { saveTestEvidence(p, { projectFingerprint: projectFingerprint(p, loadTestDeclaration(p)), commands: [{ id: "unit", stdout: "ok", stderr: "" }] }); assert.ok(codes(gate(p)).includes("MALFORMED_TEST_EVIDENCE")); } finally { cleanup(p); } });
test("merge blocks missing implementation or review retests", () => { const p = context(); try { assert.ok(codes(gate(p, { retest: { implementation: false, review: true } })).includes("RETEST_AFTER_IMPLEMENTATION_REQUIRED")); assert.ok(codes(gate(p, { retest: { implementation: true, review: false } })).includes("RETEST_AFTER_REVIEW_REQUIRED")); fs.writeFileSync(path.join(p, "source.txt"), "changed\n"); assert.ok(codes(gate(p)).includes("RETEST_AFTER_IMPLEMENTATION_REQUIRED")); } finally { cleanup(p); } });
test("merge blocks unresolved and invalid dismissed reviews", () => { const unresolved = items([{ source: "CodeRabbit", externalId: "cr-open", body: "Fix it", actionable: true, status: "unresolved", firstSeenAt: timestamp, lastSeenAt: timestamp }]); const p = context({ review: reviewState({ unresolvedBlockers: 1, mergeBlocked: true }), reviewItems: unresolved }); try { assert.ok(codes(gate(p)).includes("UNRESOLVED_ACTIONABLE_REVIEW")); } finally { cleanup(p); } const invalid = items([{ source: "GPT", externalId: "dismissed", body: "Skip", actionable: false, status: "dismissed", firstSeenAt: timestamp, lastSeenAt: timestamp }]); const q = context({ reviewItems: invalid }); try { assert.ok(codes(gate(q)).includes("DISMISSED_REVIEW_MISSING_GPT_DECISION")); } finally { cleanup(q); } });
test("merge blocks unclear review state while Qodo remains unavailable but non-blocking", () => { const p = context({ review: reviewState({ ingestionStatus: "failed", failureReason: "CodeRabbit unavailable" }) }); try { assert.ok(codes(gate(p)).includes("REVIEW_STATUS_UNCLEAR")); } finally { cleanup(p); } const q = context(); try { const result = gate(q); assert.equal(result.allowed, true); assert.deepEqual(result.evidence.review.unavailableSources, ["Qodo"]); } finally { cleanup(q); } });
test("merge blocks absent, stale, and wrongly scoped GPT approval", () => { const p = context(); try { assert.ok(codes(gate(p, { approval: null })).includes("MISSING_GPT_APPROVAL")); assert.ok(codes(gate(p, { approval: { ...input().approval, stale: true } })).includes("STALE_GPT_APPROVAL")); assert.ok(codes(gate(p, { approval: { ...input().approval, headCommit: "other" } })).includes("GPT_APPROVAL_SCOPE_MISMATCH")); } finally { cleanup(p); } });
test("merge blocks missing or invalid project metadata", () => { const p = context(); try { assert.ok(codes(gate(p, { project: null })).includes("MISSING_PROJECT_METADATA")); assert.ok(codes(gate(p, { project: "bad/project" })).includes("MISSING_PROJECT_METADATA")); } finally { cleanup(p); } });
test("merge blocks dirty trees, wrong branches, and incomplete or unmergeable PRs", () => { const p = context(); try { assert.ok(codes(gate(p, { dirty: true })).includes("DIRTY_WORKTREE")); assert.ok(codes(gate(p, { currentBranch: "other" })).includes("WRONG_BRANCH")); assert.ok(codes(gate(p, { pr: null })).includes("MISSING_PR_METADATA")); assert.ok(codes(gate(p, { pr: { ...input().pr, mergeable: null } })).includes("PR_MERGEABILITY_UNCLEAR")); assert.ok(codes(gate(p, { pr: { ...input().pr, mergeable: false } })).includes("PR_UNMERGEABLE")); } finally { cleanup(p); } });
test("merge blocks next phase before a result is recorded and invalid state", () => { const p = context(); try { assert.ok(codes(gate(p, { nextPhaseRequested: true })).includes("NEXT_PHASE_BEFORE_MERGE_RECORDED")); fs.writeFileSync(path.join(p, "STATE.json"), "{}"); assert.ok(codes(evaluateMergeReadiness({ projectPath: p, state: {}, input: input(), now: timestamp })).includes("INVALID_STATE")); } finally { cleanup(p); } });
test("all gates passing saves a deterministic readiness report and only emits a non-executing relay", () => { const p = context(); try { const result = gate(p); assert.equal(result.allowed, true); const report = saveMergeReadinessReport(p, result); assert.match(report, /out[\\/]merge_reports[\\/]phase-8-pr-8-legacy\.json$/u); const checked = saveMergeReadinessReport(p, { ...result, reportMode: "merge-check" }); assert.match(checked, /out[\\/]merge_reports[\\/]phase-8-pr-8-merge-check\.json$/u); assert.notEqual(report, checked); const relay = createMergeRelay(result); assert.equal(relay.executable, false); assert.equal(relay.kind, "merge-relay"); } finally { cleanup(p); } });
test("merge report storage contains malicious phase values", () => { const p = context(); try { const result = gate(p); for (const phase of ["../x", "../../evil", "/tmp/x", "phase/8", "phase\\8", ""]) { const report = saveMergeReadinessReport(p, { ...result, phase }); assert.equal(path.dirname(report), path.join(p, "out", "merge_reports")); assert.equal(path.basename(report), "phase-unknown-pr-8-legacy.json"); } for (const reportMode of ["../x", "../../evil", "/tmp/x", "mode/x", "mode\\x", ""]) { const report = saveMergeReadinessReport(p, { ...result, reportMode }); assert.equal(path.dirname(report), path.join(p, "out", "merge_reports")); assert.equal(path.basename(report), "phase-8-pr-8-unknown.json"); } } finally { cleanup(p); } });
test("merge result recording is schema-validated, append-only, and enables the next phase", () => { const p = context(); try { const before = fs.readFileSync(path.join(p, "BUILD_LOG.md"), "utf8"); const result = gate(p); const recorded = recordMergeResult({ projectPath: p, state: loadState(p), report: result, mergeCommit: "merge456", actor: "approved-executor", mergedAt: timestamp }); const saved = loadState(p); assert.equal(saved.mergeGate.nextPhaseEligible, true); assert.equal(saved.mergeGate.mergeResult.mergeCommit, "merge456"); assert.ok(fs.readFileSync(path.join(p, "BUILD_LOG.md"), "utf8").startsWith(before)); assert.equal(recorded.result.pr, "8"); } finally { cleanup(p); } });
test("merge fixture commands reject missing and non-object fixture data with typed errors", () => { const missing = cliContext({}); try { assert.throws(() => run(["merge", "relay", "demo", "--config", missing.config]), (error) => code(error, "INVALID_ARGUMENT")); } finally { cleanup(missing.directory); } for (const value of [null, [], "text", 42, true]) { const c = cliContext(value); try { assert.throws(() => run(["merge", "check", "demo", "--config", c.config, "--fixture", c.fixture]), (error) => code(error, "MERGE_FIXTURE_INVALID")); } finally { cleanup(c.directory); } } });
test("merge result state combinations are schema-validated", () => { const noResult = { ...state, mergeGate: { readiness: "blocked", implementationRetested: false, reviewRetested: false, nextPhaseEligible: false, mergeResult: null } }; assert.doesNotThrow(() => validateState(noResult)); const result = mergeResult(); assert.throws(() => validateState({ ...state, mergeGate: { readiness: "blocked", implementationRetested: true, reviewRetested: true, nextPhaseEligible: true, mergeResult: result } }), (error) => code(error, "INVALID_STATE")); assert.doesNotThrow(() => validateState({ ...state, mergeGate: { readiness: "merged", implementationRetested: true, reviewRetested: true, nextPhaseEligible: true, mergeResult: result } })); });
